"""Add JobCategory model

Revision ID: 135d437d5949
Revises: 13d8108ffd00
Create Date: 2026-03-05 17:02:00.157197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135d437d5949'
down_revision: Union[str, Sequence[str], None] = '13d8108ffd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_categories_id'), 'job_categories', ['id'], unique=False)
    op.create_index(op.f('ix_job_categories_name'), 'job_categories', ['name'], unique=True)
    op.add_column('jobs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'job_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'category_id')
    op.drop_index(op.f('ix_job_categories_name'), table_name='job_categories')
    op.drop_index(op.f('ix_job_categories_id'), table_name='job_categories')
    op.drop_table('job_categories')
    # ### end Alembic commands ###
