"""upgrade_job_industry_array

Revision ID: 13d8108ffd00
Revises: bf043f312807
Create Date: 2025-12-23 21:15:43.062484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d8108ffd00'
down_revision: Union[str, Sequence[str], None] = 'bf043f312807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.add_column('jobs', sa.Column('industry_id', sa.Integer(), nullable=True))
    
    # FIX: Handle existing NULL values before setting nullable=False
    op.execute("UPDATE jobs SET salary_min = 0 WHERE salary_min IS NULL")
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.INTEGER(),
               nullable=False)
               
    op.execute("UPDATE jobs SET location = 'Unknown' WHERE location IS NULL")
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
               
    op.create_foreign_key(None, 'jobs', 'industries', ['industry_id'], ['id'])
    op.drop_column('jobs', 'industry')
    
    # Manual update for job_type: Convert Enum to ARRAY
    # ... (rest of the code)
    
    # Manual update for job_type: Convert Enum to ARRAY
    # Since we can't easily CAST Enum to ARRAY(Enum) without explicit USING, and existing data is single Enum,
    # we might need to handle this. If data is unimportant, we can drop and recreate.
    # Assuming we want to preserve or just switch:
    # "job_type": Enum -> ARRAY(Enum)
    # Step 1: Drop old column (or alter with USING, but simplest is drop/add if dev env)
    # But user might want data. 
    # Let's try: Alter column with USING `ARRAY[job_type]`
    
    # NOTE: PostgreSQL needs the Type to be compatible.
    # We are changing from "jobtype" Enum to ARRAY("jobtype").
    # op.alter_column('jobs', 'job_type', type_=sa.ARRAY(sa.Enum(name='jobtype')), postgresql_using='ARRAY[job_type]')
    
    # For now, to be safe and simple given I don't know exact PG version issues with Enum arrays via Alembic:
    # I will drop 'job_type' and add it back as ARRAY.
    op.drop_column('jobs', 'job_type')
    op.add_column('jobs', sa.Column('job_type', sa.ARRAY(sa.Enum('FULL_TIME', 'PART_TIME', 'REMOTE', 'HYBRID', 'CONTRACT', name='jobtype')), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobs', 'industry_id')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    # Downgrade job_type
    op.drop_column('jobs', 'job_type')
    op.add_column('jobs', sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'REMOTE', 'HYBRID', 'CONTRACT', name='jobtype'), nullable=True))

    op.drop_table('industries')
    # ### end Alembic commands ###
