"""add cv_url to users

Revision ID: 45c3ebfab8ef
Revises: dc200805957f
Create Date: 2025-11-27 19:56:09.737243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c3ebfab8ef'
down_revision: Union[str, Sequence[str], None] = 'dc200805957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cv_url')
    op.drop_column('interviews', 'decision')
    # ### end Alembic commands ###
