"""Add context_data to CampaignStage

Revision ID: 6c088ffddabc
Revises: d20f550610d1
Create Date: 2026-03-11 16:48:37.923936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c088ffddabc'
down_revision: Union[str, Sequence[str], None] = 'd20f550610d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_stages', sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_stages', 'context_data')
    # ### end Alembic commands ###
