"""upgrade_jobs_table

Revision ID: bf043f312807
Revises: 45c3ebfab8ef
Create Date: 2025-12-23 19:38:22.085220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf043f312807'
down_revision: Union[str, Sequence[str], None] = '45c3ebfab8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types first
    job_type_enum = sa.Enum('FULL_TIME', 'PART_TIME', 'REMOTE', 'HYBRID', 'CONTRACT', name='jobtype')
    experience_level_enum = sa.Enum('INTERN', 'FRESHER', 'JUNIOR', 'SENIOR', 'MANAGER', name='experiencelevel')
    
    # Create the types in the database
    job_type_enum.create(op.get_bind(), checkfirst=True)
    experience_level_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('jobs', sa.Column('job_type', job_type_enum, nullable=True))
    op.add_column('jobs', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', experience_level_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'industry')
    op.drop_column('jobs', 'job_type')
    
    # Drop Enum types
    sa.Enum(name='experiencelevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='jobtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
