"""Add AI review fields to Application

Revision ID: d50de59c9aa5
Revises: e3e1a917a92a
Create Date: 2026-03-09 14:45:36.446224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd50de59c9aa5'
down_revision: Union[str, Sequence[str], None] = 'e3e1a917a92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('match_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('is_potential', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('short_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'short_summary')
    op.drop_column('applications', 'missing_skills')
    op.drop_column('applications', 'matched_skills')
    op.drop_column('applications', 'is_potential')
    op.drop_column('applications', 'match_score')
    # ### end Alembic commands ###
